### ISSUE TITLE
Extend templates

### ISSUE THREAD

**Issue by carlotm** [novaframework/nova#205] opened 2023-04-25 16:48 UTC
Hi,

I am using nova from git, `master` branch.

I am trying to extend a template, so in `src/views/myproject_main.dtl` I put:

```
{% extends "layouts/root.dtl" %}

{% block "main" %}
  {{message}}
{% endblock "main" %}
```

While `src/views/layouts/root.dtl` is:

```
<html>
<body>
  {% block "main" %}{% endblock "main" %}
</body>
</html>
```

If I run `rebar3 compile` I got:

```
=WARNING REPORT==== 25-Apr-2023::18:28:52.288964 ===
Description: "Server authenticity is not verified since certificate path validation is not enabled"
     Reason: "The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."

===> Verifying dependencies...
===> Running erlydtl...
===> Compiling src/views/lss_main.dtl failed
```

Is that a known limitation, or maybe I'm doing something wrong?

Thank you

**Comment by Taure** [comment] 2023-04-25 17:43
I am not aware of that we should have a issue with this.

I can try it out and see what I can find. Do you have any example repo where I  could reproduce this or is it only two files like above in a application?

**Comment by carlotm** [comment] 2023-04-26 04:35
Here it is:
https://github.com/carlotm/lazyspeaker

(it's just the scaffolded project + the extend)

Thank you!

**Comment by burbas** [comment] 2023-04-26 15:37
Hi,

Sorry for the late response. The problem is that you can't define blocks as strings. In your example it should be

`{% block main %}Hello world{% endblock %}`

Observe that you don't have to explicitly say which block you are closing (Nested scopes are allowed but you can't have overlaps).

I'll try to look into the erlydtl-plugin and why it does not return any errors when they occur. I took @Taure code base and update it accordingly if you'd like to view an example of how `extends` could look like; https://github.com/novaframework/issue205


Best,
Niclas

**Closed by burbas** 2023-04-26 15:37 UTC
Labels: bug

**Comment by burbas** [comment] 2023-04-26 15:38
Closed the issue for now. Feel free to open a new one if you see a potential bug!

**Comment by carlotm** [comment] 2023-04-26 18:15
Fantastic! Thank you
